### ISSUE TITLE
How does login work?

### ISSUE THREAD

**Issue by rachelroks9** [David-Sparky/TakeMeHomeTonight#10]

**Comment by cmrenus** [comment]
On the backend, login utilizes, the cas-authentication module. Due to Cross Origin Request issues, since out site and RPI's CAS system are on separate domains, the module code had to be redone to send the URL and allow the browser to redirect the user instead of the server doing the redirect. After a user logs into CAS, if they are authenticated and are a user, the server redirects them to our landing page. In addition, it adds a session token and a cookie for the user to authenticate and make sure the user is who they are. If they do not, it will redirect them back to the login & signup.
