### ISSUE TITLE
How does sign in work?

### ISSUE THREAD

**Issue by rachelroks9** [David-Sparky/TakeMeHomeTonight#11]

**Comment by cmrenus** [comment]
When a user clicks sign up, it redirects them to the CAS login. Since our user base is only RPI students, that is our way to handle that. After signing in through there, it will redirect the user to the sign up page. From here they can enter some details about themselves. Once they click signup, their information will be pushed to the user collection within the database. If a user already has an account and tries to sign up, it will just redirect them to the landing page and notify them they already have an account.
