### ISSUE TITLE
How does settings work?

### ISSUE THREAD

**Issue by rachelroks9** [David-Sparky/TakeMeHomeTonight#13]

**Comment by cmrenus** [comment]
The settings page is split up among multiple tabs. The first one is profile information. Here they can change their first name, last name and even set their vehicle information. Vehicle information isn't required since not everyone has a vehicle. When creating a ride, the form will pull this information for ease of use. 
The second tab is a users offered rides. The first section there they can view their offered rides. When they click on the ride, it expands showing the amount of available seats, pending and accepted riders, and then a button which will delete that offered ride. From here they can confirm riders for that ride or remove the rider. The next section there is a users offer for needed rides. It shows some basic information along with the status of the ride, accpeted or pending, and a button where you can delete your request.
The third tab is requested rides. The first section here shows the rides that you need. when clicking on a ride, it also drops down displaying the drivers that have requested and a delete button for this needed ride. Here you can also confirm or delete a driver for this ride. The second section shows any requests a user has on available rides. Here they can see the status of their request as well as delete their request.
