### ISSUE TITLE
How does add a ride work?

### ISSUE THREAD

**Issue by rachelroks9** [David-Sparky/TakeMeHomeTonight#16]

**Comment by minars** [comment]
Add a ride is a form that allows users to offer other users rides to a place they are going, such as Walmart. It allows the user to define when and where they will be going. It also gives them the choice to to define how many available seats they have in their car. If the user has defined their car in their profile then it will auto fill, otherwise it allows the user to fill in all of the information. Then they click submit and the ride is now listed as an available ride.
