### ISSUE TITLE
Data Model

### ISSUE THREAD

**Issue by rachelroks9** [David-Sparky/TakeMeHomeTonight#20]

**Comment by minars** [comment]
tmht

```
requested
    "_id" : ObjectId("1234567981324789123456"),
"departLocation" : "Dearting",
"departDate" : "depart date",
"departTime" : "depart time",
"destination" : "Destination",
"cost" : "Cost - or price/item willing to pay",
"drivers" : [
        {
                "rcs" : "rcs",
                "status" : "status - pending or accepted"
        }
],
"rcs" : "owner",
"accepted" : bool


offered
"_id" : ObjectId("1234567981324789123456"),
"car" : {
        "make" : "make",
        "model" : "model",
        "color" : "color",
        "license" : "license"
},
"departLocation" : "departing",
"departDate" : "Depart Date",
"departTime" : "Dapart Time",
"destination" : "destination",
"cost" : "cost",
"seats" : total number of seats,
"availableseats" : number of available sears,
"owner" : "owner",
"riders" : [
        {
                "rcs" : "rcs",
                "status" : "status - pending or accepted"
        }
]


users
 "_id" : ObjectId("571d0d345b837d1100c9d22c"),
"rcs" : "rcs",
"firstName" : "First Name",
"lastName" : "Last Name",
"car" : {
        "make" : "make",
        "model" : "model",
        "color" : "color",
        "license" : "license"
}
```

That is the collections and how they are setup within the database.

The requested collection is for rides that were requested by someone. As in they clicked on I need a ride. The I need a ride button allows the user to submit a request for a ride which is added to this collection. From here it can be pulled out by a number of different text options and displayed onto the pages.

The offered collection is for users who are going someone and are offering to give rides to people. This needs to store a car and a bit more information about the total amount of seats and seats available. All of this is stored within this offered collection.

Finally the users collection is a collection of the users who have signed in. They make a profile and write in their name as well as enter a car if they have one. This can be used later in the offer a ride form because it automatically adds in the car information
